name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@develop
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
      # ============= InvisiRisk Setup End =============

      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libwayland-dev \
            libxkbcommon-dev \
            libudev-dev \
            libasound2-dev

      - name: Build
        run: cargo build --verbose

    
      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@develop
        with:
          api_url: "https://app.stage.invisirisk.com"
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
